### ISSUE TITLE
Лог с ошибкой можно сделать проще

### ISSUE THREAD

**Issue by vladimirkoba** [gutop84/MyTestFramework#1]
https://github.com/gutop84/MyTestFramework/blob/59589f0cabcb1c6faa2260fa4180292c70bcc414/src/main/java/frameworklogic/CustomJUnit.java#L38

В таких случаях делают через logger.error("text", e)

**Comment by gutop84** [comment]
#1 issue - По-моему e.getMessage() было нагляднее
