### ISSUE TITLE
Всё статичное

### ISSUE THREAD

**Issue by vladimirkoba** [gutop84/MyTestFramework#3]
"Ребята, по домашке с тестовом фреймворком. Не делайте все на статических методах. 
Оставьте один статический метод, и в нем сделайте вызов фреймворка)"

**Comment by gutop84** [comment]
#3 issue - теперь создаётся пустой объект FrameworkObjectClass, который обращается к внутренним нестатическим методам с неизменённой логикой.
(Или подразумевалось разстатичить методы из ReflectionHelper?)
